In [1]:
import bonhomme_manresa

In [2]:
from linearmodels.datasets import wage_panel

wage_panel_df = wage_panel.load()

wage_panel_df.set_index(["nr", "year"], inplace=True)
y = wage_panel_df["lwage"]
x = wage_panel_df.drop(columns=["occupation", "lwage", "black", "hisp", "educ"])
display(x)
display(y)

exper  hours  married  union  expersq
nr    year                                       
13    1980      1   2672        0      0        1
      1981      2   2320        0      1        4
      1982      3   2940        0      0        9
      1983      4   2960        0      0       16
      1984      5   3071        0      0       25
...           ...    ...      ...    ...      ...
12548 1983      8   2080        1      0       64
      1984      9   2080        1      1       81
      1985     10   2080        1      0      100
      1986     11   2080        1      1      121
      1987     12   3380        1      1      144

[4360 rows x 5 columns]

nr     year
13     1980    1.197540
       1981    1.853060
       1982    1.344462
       1983    1.433213
       1984    1.568125
                 ...   
12548  1983    1.591879
       1984    1.212543
       1985    1.765962
       1986    1.745894
       1987    1.466543
Name: lwage, Length: 4360, dtype: float64

In [3]:
N = x.index.get_level_values(0).nunique()
T = x.index.get_level_values(1).nunique()
K = x.shape[1]
x = x.values.reshape(N, T, K).astype(float)
y = y.values.reshape(N, T, 1).astype(float)
x, y

(array([[[1.000e+00, 2.672e+03, 0.000e+00, 0.000e+00, 1.000e+00],
         [2.000e+00, 2.320e+03, 0.000e+00, 1.000e+00, 4.000e+00],
         [3.000e+00, 2.940e+03, 0.000e+00, 0.000e+00, 9.000e+00],
         ...,
         [6.000e+00, 2.864e+03, 0.000e+00, 0.000e+00, 3.600e+01],
         [7.000e+00, 2.994e+03, 0.000e+00, 0.000e+00, 4.900e+01],
         [8.000e+00, 2.640e+03, 0.000e+00, 0.000e+00, 6.400e+01]],
 
        [[4.000e+00, 2.484e+03, 0.000e+00, 0.000e+00, 1.600e+01],
         [5.000e+00, 2.804e+03, 0.000e+00, 0.000e+00, 2.500e+01],
         [6.000e+00, 2.530e+03, 0.000e+00, 0.000e+00, 3.600e+01],
         ...,
         [9.000e+00, 2.164e+03, 0.000e+00, 0.000e+00, 8.100e+01],
         [1.000e+01, 2.749e+03, 0.000e+00, 0.000e+00, 1.000e+02],
         [1.100e+01, 2.476e+03, 0.000e+00, 0.000e+00, 1.210e+02]],
 
        [[4.000e+00, 2.332e+03, 1.000e+00, 0.000e+00, 1.600e+01],
         [5.000e+00, 2.116e+03, 1.000e+00, 0.000e+00, 2.500e+01],
         [6.000e+00, 2.500e+03, 1.000e+00,

In [8]:
bonhomme_manresa.grouped_fixed_effects(y[0:60], x[0:60], 3, max_iter=1000, tol=1e-8, gfe_iterations=1000)

(array([[ 8.49758982e-02],
        [ 3.72342440e-05],
        [ 1.63291883e-01],
        [ 5.82514603e-02],
        [-1.15772476e-03]]),
 array([[ 0.86504062,  0.87677102,  0.83024195,  0.7885461 ,  0.67492121,
          0.71294085,  0.70199323,  0.71317915],
        [ 1.43280283,  1.51283731,  1.4381133 ,  1.43451408,  1.40989616,
          1.37917821,  1.23577421,  1.31700442],
        [ 1.35961534,  0.14116958,  0.31030368,  0.47155626, -4.1209801 ,
          0.73773808,  0.734838  ,  0.80156139]]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0]),
 859,
 68.11082939847141)